### ISSUE TITLE
prune: failed to remove icons from the Launchpad. Check log for details.

### ISSUE THREAD

**Issue by ramsnerm** [nicolodiamante/prune#1]
Hi!

Thanks for this tool and your effort. I was looking for such a tool. I tried it but I get following message:

prune: failed to remove icons from the Launchpad. Check log for details.

In the log file is:
Error: unable to open database "/private/var/folders/f5/y3b430nj1g9fxq4drd7mjkgc0000gr/0/com.apple.dock.launchpad": unable to open database file

I try to use the tool on Sonoma.

When I check the script I saw that you gather with the command
`sudo find /private/var/folders -name com.apple.dock.launchpad`

the database file path.

On my system I have different users and therefore I get 6 "paths"
```
/private/var/folders/f5/y3b430nj1g9fxq4drd7mjkgc0000gr/0/com.apple.dock.launchpad
/private/var/folders/26/j8r9bbdx5hl8vqrhnvhd8tw40000gs/0/com.apple.dock.launchpad
/private/var/folders/9z/yl8cgstx4gj0fs_gp7h6lpy00000gn/0/com.apple.dock.launchpad
/private/var/folders/g3/kyl6rvjj5wndt4lqmlz5d_rm0000gs/0/com.apple.dock.launchpad
/private/var/folders/15/lfx_k24d77zbz4g6zl3hbmb00000gn/0/com.apple.dock.launchpad
/private/var/folders/2p/y0fw_39n4rx8hx5vkhjpq9ph0000gr/0/com.apple.dock.launchpad
```

Out of the log I can see that you take the first entry only, but for my user I would need the third line 

When I use this path and the command from the script to hide the App icon it works.
`sudo sqlite3 /private/var/folders/9z/yl8cgstx4gj0fs_gp7h6lpy00000gn/0/com.apple.dock.launchpad/db/db "DELETE FROM apps WHERE title='Aktien';" && killall Dock`

Have you a tip for me to solve the issue?
Thanks

**Comment by nicolodiamante** [comment]
Hello @ramsnerm,

Thanks for bringing this to my attention. I’ve reviewed your issue and made some updates to the script to better handle systems with multiple users. Specifically, the script now dynamically try to find the correct ‘com.apple.dock.launchpad’ database path for the current user. This should resolve the issue you encountered.

You can download the updated script from the [repository](https://github.com/nicolodiamante/prune).

Please give it a try and let me know if it resolves the issue.

Thank you for your feedback!
Nicolò

**Comment by ramsnerm** [comment]
Hi Nicolò!
Thanks for the update. That works!
Martin
